[package]
name = "dxp-logging"
version = "0.1.1"
edition = "2021"

[dependencies]
tracing-subscriber = { version = "^0.3.18", features = ["env-filter"] }
tracing = "^0.1.40"
tracing-appender = { version = "^0.2.3", optional = true }

[features]
# default = ["log-file"]
default = []
log=[]
log-file=["dep:tracing-appender"]
